### ISSUE TITLE
implementing mvvm with custom view - question - help

### ISSUE THREAD

**Issue by lazarvgd** [Arigar/AndroidMVVMExample#1]
Hi, I have problem to switch my architecture to MVVM due to some problems:

I have extended View class in order to draw custom view([epg screen for IPTV](https://en.wikipedia.org/wiki/Electronic_program_guide)).
So I have Activity where I instantiated CustomView class and used `setContentView(customView);`
The problem is that I have class(I named it DrawService) which are in charge for drawing on canvas(DrawService) depending on objects that are made by factory class. DrawService requires `canvas`
object in order to draw.

Also, during the execution of the activity I catching key press in order to make navigation on screen.
I am doing that from Activity with this line of code ` epgCustomView.getEpgScreenService().onClick(keyCode);`

I can draw UML diagram if that could make better picture of my current architecture?

Please let me know if I need to explain something more in details.
Thanks 

EDIT:
Summary:
Activity instantiate CustomView object and  set it with  `setContentView(customView);`
CustomView extends View and has instance of DrawService object which requires canvas to be passed in constructor in order to draw.

**Comment by Arigar** [comment]
Hi. If I understand correctly, problem is your get access to canvas only inside onDraw() method. So you can create and use DrawService only there, is not it?

Can you give me more explanation about catching keypress?  I don't find out what wrong with it. 

Yes, UML diagram will help me understand your architecture better. Maybe you can give some demo app.

P.S.
I am learning English now. Please, point to my mistakes if I made them.

**Comment by lazarvgd** [comment]
Hi! No problem for English. Give me a little time, I will upload all information just to arrive in the office.

Let me upload a part of code and you will get the point.

Здравствуйте

**Comment by Arigar** [comment]
I added you as collaborator.

**Comment by lazarvgd** [comment]
Thanks for adding me as collaborator.

the view class:```

public class EpgRectangleView extends View {
private DrawService drawService;

protected void onDraw(Canvas canvas) {
drawService  = new DrawService(canvas); //this performs all drawings on canvas
}
...}
```
the DrawService class requires **Canvas** object from onDraw method in order to perform drawing. I have implemented all drawings in this class due to separation of concerns.
The problem is that I don't know how to send DrawService object thought data binding. How to tell pass **canvas** object to **drawService** object

Unfortunately my UML looks like crap. So I will try to illustrate you my architecture;

I will try to draw it and post it.

**Comment by Arigar** [comment]
I suppose that your DrawService does most of work. Can you give me interface of its main functions with comments.

**Comment by lazarvgd** [comment]
Here is [pastebin link](https://pastebin.com/FC8TWDeG), this is DrawService;

[customView](https://pastebin.com/VgM44pwF)

[activity](https://pastebin.com/6uihZPth)

please let me know if you need anything else.

**Comment by Arigar** [comment]
I did not find out what do you want use as model. You mention EpgActivityViewModel, but do not use it.

For successful using MVVM needs clear understand what is model and what is view.  ViewModel is only bridge between them. 

Model, for example, contains list of channels.
Every channel has name, description, list of TV programs and other fields that describe channel. 
Program is name, duration.

This model can be used in Android or Swing, it does not use platform specific features.

View is platform-depended UI, that can show your model.

ViewModel is platform-depended adapter between View and Model. ViewModel can adapt model data for view, react for user events.

Try split your app into this components and implement MVVM will be easily.

**Comment by lazarvgd** [comment]
That is correct, I don't know how to do it.
I have made class viewModel, but don't know how to pass and call drawService if i explicitly call it from customView constructor? Do you get the point?
sorry about this, my knowledge is limited and I am still junior.
How would you solve this? any ideas?

**Comment by Arigar** [comment]
What do you need know about channel for appropriate displaying on screen?

**Comment by lazarvgd** [comment]
We have miss understood. Question is, how can I send service object to view, so view can  pass canvas to drawService? Also I have to pass keys to service(which is in view) in order to redraw whole screen when key is pressed.

**Comment by Arigar** [comment]
Ok, obviously I don't understand how you want use android binding and MVVM.

Based on the current code you need simple setter in your view and set appropriate service in activity. This is not MVVM and data binding, because this architecture isn't applicable for this.
About keys. You don't know how to get the code or how to call the screen update?

**Comment by lazarvgd** [comment]
I understand the way how to send some data view mvvm to view. How will I tell view to to call Serivce class and pass canvas to it?

**Comment by Arigar** [comment]
Let's make it clear. In your code I found two services: EpgScreenService and EpgDrawService. What kind of service are we talking about?

**Comment by lazarvgd** [comment]
Oh, sorry, I made a mistake, I have omitted screen service, here it is. maybe this will give you my point.
https://pastebin.com/HfBVHpBW
please sorry :(

**Comment by Arigar** [comment]
I finally understood what do you mean. But it is impossible, in MVVM model (I suppose, it is EpgScreenServiceImpl) don't know about view. Model should not get something from view (In your case it is canvas). Your arhitecture close to MVP pattern

**Comment by Arigar** [comment]
I made mistake, MVC, not MVP

**Comment by lazarvgd** [comment]
Aha, Thanks!
Sorry if you lost whole day on my issue. :(

I will left this as it is until I figure out how to change from MVC to MVVM this part of code.

Поздрав,
Лазар

**Comment by Arigar** [comment]
It is OK. I had good practice in English.
